name: buildx

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get shortened commit hash for tagging
        id: shortened_hash
        run: echo ::set-output name=hash::$(git log -1 --format=%h)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PASS }}
      - name: Build & push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/ewilken/docker-mailserver:latest
            ghcr.io/ewilken/docker-mailserver:${{ steps.shortened_hash.outputs.hash }}
